import psycopg2
import pandas as pd 

import os
# cargamos dotenv
from dotenv import load_dotenv
load_dotenv()

# 1 Abrimos el df de embeddgins que queremos subir!



df_final = pd.read_csv("news_similarity/embedding_sp500.csv")

# borrar unmmaed 0
df_final.drop('Unnamed: 0',axis=1,inplace=True)

df_final.columns.to_list()

my_list = df_final.columns.to_list()
result_string = ', '.join(my_list)
print(result_string)



conn = psycopg2.connect(
                host=os.getenv("HOST_TFM") ,
                user =os.getenv("USER_TFM") ,
                password=os.getenv("PASSWORD_TFM"),
                port=os.getenv("PORT_TFM"),
                database=os.getenv("DATABASE_TFM")
        )

cursor=conn.cursor()

# cerrar
cursor.close()
conn.close()


cursor.execute("DROP TABLE public.embeddings_sentencetransformer;")

conn.commit()

cursor.execute(f""" CREATE TABLE IF NOT EXISTS public.embeddings_sentencetransformer (
                        
            TresM float4 ,
            A_O_Smith float4 ,
            Abbott_Laboratories float4 ,
            AbbVie float4 ,
            Accenture float4 ,
            Activision_Blizzard float4 ,
            ADM float4 ,
            Adobe_Inc float4 ,
            ADP float4 ,
            Advance_Auto_Parts float4 ,
            AES_Corporation float4 ,
            Aflac float4 ,
            Agilent_Technologies float4 ,
            Air_Products_and_Chemicals float4 ,
            Akamai float4 ,
            Alaska_Air_Group float4 ,
            Albemarle_Corporation float4 ,
            Alexandria_Real_Estate_Equities float4 ,
            Align_Technology float4 ,
            Allegion float4 ,
            Alliant_Energy float4 ,
            Allstate float4 ,
            Alphabet_Inc float4 ,
            Altria float4 ,
            Amazon float4 ,
            Amcor float4 ,
            AMD float4 ,
            Ameren float4 ,
            American_Airlines_Group float4 ,
            American_Electric_Power float4 ,
            American_Express float4 ,
            American_International_Group float4 ,
            American_Tower float4 ,
            American_Water_Works float4 ,
            Ameriprise_Financial float4 ,
            AmerisourceBergen float4 ,
            Ametek float4 ,
            Amgen float4 ,
            Amphenol float4 ,
            Analog_Devices float4 ,
            Ansys float4 ,
            Aon float4 ,
            APA_Corporation float4 ,
            Apple_Inc float4 ,
            Applied_Materials float4 ,
            Aptiv float4 ,
            Arch_Capital_Group float4 ,
            Arista_Networks float4 ,
            Arthur_J_Gallagher_and_Co float4 ,
            Assurant float4 ,
            ATandT float4 ,
            Atmos_Energy float4 ,
            Autodesk float4 ,
            AutoZone float4 ,
            AvalonBay_Communities float4 ,
            Avery_Dennison float4 ,
            Axon_Enterprise float4 ,
            Baker_Hughes float4 ,
            Ball_Corporation float4 ,
            Bank_of_America float4 ,
            Bath_and_Body_Works float4 ,

            Baxter_International float4 ,
            BD float4 ,
            W_R_Berkley_Corporation float4 ,
            Berkshire_Hathaway float4 ,
            Best_Buy float4 ,
            Bio_Rad float4 ,
            Bio_Techne float4 ,
            Biogen float4 ,
            BlackRock float4 ,
            BNY_Mellon float4 ,
            Boeing float4 ,
            Booking_Holdings float4 ,
            BorgWarner float4 ,
            Boston_Properties float4 ,
            Boston_Scientific float4 ,
            Bristol_Myers_Squibb float4 ,
            Broadcom_Inc float4 ,
            Broadridge_Financial_Solutions float4 ,
            Brown_and_Brown float4 ,
            Bunge_Limited float4 ,
            CH_Robinson float4 ,
            Cadence_Design_Systems float4 ,
            Caesars_Entertainment float4 ,
            Camden_Property_Trust float4 ,
            Campbell_Soup_Company float4 ,
            Capital_One float4 ,
            Cardinal_Health float4 ,
            CarMax float4 ,
            Carnival_Corporation_and_plc float4 ,
            Carrier_Global float4 ,
            Catalent float4 ,
            Caterpillar_Inc float4 ,
            Cboe_Global_Markets float4 ,
            CBRE_Group float4 ,
            CDW float4 ,
            Celanese float4 ,
            Centene_Corporation float4 ,
            CenterPoint_Energy float4 ,
            Ceridian float4 ,
            CF_Industries float4 ,
            Charles_River_Laboratories float4 ,
            Charles_Schwab_Corporation float4 ,
            Charter_Communications float4 ,
            Chevron_Corporation float4 ,
            Chipotle_Mexican_Grill float4 ,
            Chubb_Limited float4 ,
            Church_and_Dwight float4 ,
            Cigna float4 ,
            Cincinnati_Financial float4 ,
            Cintas float4 ,
            Cisco float4 ,
            Citigroup float4 ,
            Citizens_Financial_Group float4 ,
            Clorox float4 ,
            CME_Group float4 ,
            CMS_Energy float4 ,
            The_Coca_Cola_Company float4 ,
            Cognizant float4 ,
            Colgate_Palmolive float4 ,
            Comcast float4 ,
            Comerica float4 ,
            Conagra_Brands float4 ,
            ConocoPhillips float4 ,
            Consolidated_Edison float4 ,
            Constellation_Brands float4 ,
            Constellation_Energy float4 ,
            CooperCompanies float4 ,
            Copart float4 ,
            Corning_Inc float4 ,
            Corteva float4 ,
            CoStar_Group float4 ,
            Costco float4 ,
            Coterra float4 ,
            Crown_Castle float4 ,
            CSX_Corporation float4 ,
            Cummins float4 ,
            CVS_Health float4 ,
            DR_Horton float4 ,
            Danaher_Corporation float4 ,
            Darden_Restaurants float4 ,
            DaVita_Inc float4 ,
            John_Deere float4 ,
            Delta_Air_Lines float4 ,
            Dentsply_Sirona float4 ,
            Devon_Energy float4 ,
            Dexcom float4 ,
            Diamondback_Energy float4 ,
            Digital_Realty float4 ,
            Discover_Financial float4 ,
            Disney float4 ,
            Dollar_General float4 ,
            Dollar_Tree float4 ,
            Dominion_Energy float4 ,
            Domino float4 ,
            Dover_Corporation float4 ,
            Dow_Inc float4 ,
            DTE_Energy float4 ,
            Duke_Energy float4 ,
            DuPont float4 ,
            DXC_Technology float4 ,
            Eastman_Chemical_Company float4 ,
            Eaton_Corporation float4 ,
            EBay float4 ,
            Ecolab float4 ,
            Edison_International float4 ,
            Edwards_Lifesciences float4 ,
            Electronic_Arts float4 ,
            Elevance_Health float4 ,
            Eli_Lilly_and_Company float4 ,
            Emerson_Electric float4 ,
            Enphase float4 ,
            Entergy float4 ,
            EOG_Resources float4 ,
            EPAM_Systems float4 ,
            EQT float4 ,
            Equifax float4 ,
            Equinix float4 ,
            Equity_Residential float4 ,
            Essex_Property_Trust float4 ,
            The_Estée_Lauder_Companies float4 ,
            Etsy float4 ,
            Everest_Re float4 ,
            Evergy float4 ,
            Eversource float4 ,
            Exelon float4 ,
            Expedia_Group float4 ,
            Expeditors_International float4 ,
            Extra_Space_Storage float4 ,
            ExxonMobil float4 ,
            F5 float4 ,

            FactSet float4 ,
            FICO float4 ,
            Fastenal float4 ,
            Federal_Realty float4 ,
            FedEx float4 ,
            Fifth_Third_Bank float4 ,
            First_Solar float4 ,
            FirstEnergy float4 ,
            FIS float4 ,
            Fiserv float4 ,
            Fleetcor float4 ,
            FMC_Corporation float4 ,
            Ford_Motor_Company float4 ,
            Fortinet float4 ,
            Fortive float4 ,
            Fox_Corporation float4 ,
            Franklin_Templeton float4 ,
            Freeport_McMoRan float4 ,
            Garmin float4 ,
            Gartner float4 ,
            GE_HealthCare float4 ,
            Gen_Digital float4 ,
            Generac float4 ,
            General_Dynamics float4 ,
            General_Electric float4 ,
            General_Mills float4 ,
            General_Motors float4 ,
            Genuine_Parts_Company float4 ,
            Gilead_Sciences float4 ,
            Globe_Life float4 ,
            Global_Payments float4 ,
            Goldman_Sachs float4 ,
            Halliburton float4 ,
            The_Hartford float4 ,
            Hasbro float4 ,
            HCA_Healthcare float4 ,
            Healthpeak_Properties float4 ,
            Henry_Schein float4 ,
            The_Hershey_Company float4 ,
            Hess_Corporation float4 ,
            Hewlett_Packard_Enterprise float4 ,
            Hilton_Worldwide float4 ,
            Hologic float4 ,
            The_Home_Depot float4 ,
            Honeywell float4 ,
            Hormel_Foods float4 ,
            Host_Hotels_and_Resorts float4 ,
            Howmet_Aerospace float4 ,
            HP_Inc float4 ,
            Humana float4 ,
            Huntington_Bancshares float4 ,
            Huntington_Ingalls_Industries float4 ,
            IBM float4 ,
            IDEX_Corporation float4 ,
            Idexx_Laboratories float4 ,
            Illinois_Tool_Works float4 ,
            Illumina float4 ,

            Incyte float4 ,
            Ingersoll_Rand float4 ,
            Intel float4 ,
            Intercontinental_Exchange float4 ,
            International_Flavors_and_Fragrances float4 ,
            International_Paper float4 ,
            The_Interpublic_Group_of_Companies float4 ,
            Intuit float4 ,
            Intuitive_Surgical float4 ,
            Invesco float4 ,
            Invitation_Homes float4 ,
            IQVIA float4 ,
            Iron_Mountain float4 ,
            JB_Hunt float4 ,
            Jack_Henry_and_Associates float4 ,
            Jacobs_Solutions float4 ,
            Johnson_and_Johnson float4 ,
            Johnson_Controls float4 ,
            JPMorgan_Chase float4 ,
            Juniper_Networks float4 ,
            Kellogg float4 ,
            Keurig_Dr_Pepper float4 ,
            KeyBank float4 ,
            Keysight float4 ,
            Kimberly_Clark float4 ,
            Kimco_Realty float4 ,
            Kinder_Morgan float4 ,
            KLA_Corporation float4 ,
            Kraft_Heinz float4 ,
            Kroger float4 ,
            L3Harris float4 ,
            LabCorp float4 ,
            Lam_Research float4 ,
            Lamb_Weston float4 ,
            Las_Vegas_Sands float4 ,
            Leidos float4 ,
            Lennar float4 ,
            Lincoln_Financial float4 ,
            Linde_plc float4 ,
            Live_Nation_Entertainment float4 ,
            LKQ_Corporation float4 ,
            Lockheed_Martin float4 ,
            Loews_Corporation float4 ,
            Lowe float4 ,
            LyondellBasell float4 ,
            MandT_Bank float4 ,
            Marathon_Oil float4 ,
            Marathon_Petroleum float4 ,
            MarketAxess float4 ,
            Marriott_International float4 ,
            Marsh_McLennan float4 ,
            Martin_Marietta_Materials float4 ,
            Masco float4 ,
            Mastercard float4 ,
            Match_Group float4 ,
            McCormick_and_Company float4 ,
            McDonald float4 ,
            McKesson float4 ,
            Medtronic float4 ,
            Merck_and_Co float4 ,
            Meta_Platforms float4 ,
            MetLife float4 ,
            Mettler_Toledo float4 ,
            MGM_Resorts float4 ,
            Microchip_Technology float4 ,
            Micron_Technology float4 ,
            Microsoft float4 ,
            Mid_America_Apartment_Communities float4 ,
            Moderna float4 ,
            Mohawk_Industries float4 ,
            Molina_Healthcare float4 ,
            Molson_Coors_Beverage_Company float4 ,
            Mondelez_International float4 ,
            Monolithic_Power_Systems float4 ,
            Monster_Beverage float4 ,
            Moody_Corporation float4 ,
            Morgan_Stanley float4 ,
            The_Mosaic_Company float4 ,
            Motorola_Solutions float4 ,
            MSCI float4 ,
            Nasdaq float4 ,
          
            NetApp float4 ,
            Netflix float4 ,
 
            Newell_Brands float4 ,
            Newmont float4 ,
            News_Corp float4 ,
            NextEra_Energy float4 ,
            Nike float4 ,
   
            NiSource float4 ,
            Nordson_Corporation float4 ,
            Norfolk_Southern_Railway float4 ,
            Northern_Trust float4 ,
            Northrop_Grumman float4 ,
            Norwegian_Cruise_Line_Holdings float4 ,
            NRG_Energy float4 ,
            Nucor float4 ,
            Nvidia float4 ,
            NVR float4 ,

            NXP_Semiconductors float4 ,
            OReilly_Auto_Parts float4 ,
            Occidental_Petroleum float4 ,
            Old_Dominion_Freight_Line float4 ,
            Omnicom_Group float4 ,
            ON_Semiconductor float4 ,
            Oneok float4 ,
            Oracle_Corporation float4 ,
            Organon_and_Co float4 ,
            Otis_Worldwide float4 ,
            Paccar float4 ,
            Packaging_Corporation_of_America float4 ,
            Palo_Alto_Networks float4 ,
            Paramount_Global float4 ,
            Parker_Hannifin float4 ,
            Paychex float4 ,
            Paycom float4 ,
            PayPal float4 ,
            Pentair float4 ,
            PepsiCo float4 ,
            Pfizer float4 ,
            PGandE float4 ,
            Philip_Morris_International float4 ,
            Phillips_66 float4 ,
            Pinnacle_West float4 ,
            Pioneer_Natural_Resources float4 ,
            PNC_Financial_Services float4 ,
            PPG_Industries float4 ,
            PPL_Corporation float4 ,
            Principal_Financial_Group float4 ,
            Procter_and_Gamble float4 ,
            Progressive_Corporation float4 ,
            Prologis float4 ,
            Prudential_Financial float4 ,
            Public_Service_Enterprise_Group float4 ,
            PTC float4 ,
            Public_Storage float4 ,
            PulteGroup float4 ,
            Qorvo float4 ,
            Quanta_Services float4 ,
            Qualcomm float4 ,
            Quest_Diagnostics float4 ,
            Ralph_Lauren_Corporation float4 ,
            Raymond_James float4 ,
            Raytheon_Technologies float4 ,
            Realty_Income float4 ,
            Regency_Centers float4 ,
            Regeneron float4 ,
            Regions_Financial_Corporation float4 ,
            Republic_Services float4 ,
            ResMed float4 ,
            Revvity float4 ,
            Robert_Half float4 ,
            Rockwell_Automation float4 ,
            Rollins float4 ,
            Roper_Technologies float4 ,
            Ross_Stores float4 ,
            Royal_Caribbean_Group float4 ,
            SandP_Global float4 ,
            Salesforce float4 ,
            SBA_Communications float4 ,
            Schlumberger float4 ,
            Seagate_Technology float4 ,
            Sealed_Air float4 ,
            Sempra_Energy float4 ,
            ServiceNow float4 ,
            Sherwin_Williams float4 ,
            Simon_Property_Group float4 ,
            Skyworks_Solutions float4 ,
            The_JM_Smucker_Company float4 ,
            Snap_on float4 ,
            SolarEdge float4 ,
            Southern_Company float4 ,
            Southwest_Airlines float4 ,
            Stanley_Black_and_Decker float4 ,
            Starbucks float4 ,
            State_Street_Corporation float4 ,
            Steel_Dynamics float4 ,
            Steris float4 ,
            Stryker_Corporation float4 ,
            Synchrony_Financial float4 ,
            Synopsys float4 ,
            Sysco float4 ,
            T_Mobile_US float4 ,
            T_Rowe_Price float4 ,
            Take_Two_Interactive float4 ,
            Tapestry float4 ,

            Targa_Resources float4 ,
            Target_Corporation float4 ,
            TE_Connectivity float4 ,
            Teledyne_Technologies float4 ,
            Teleflex float4 ,
            Teradyne float4 ,
            Tesla float4 ,

            Texas_Instruments float4 ,
            Textron float4 ,
            Thermo_Fisher_Scientific float4 ,
            TJX_Companies float4 ,
            Tractor_Supply float4 ,
            Trane_Technologies float4 ,
            TransDigm_Group float4 ,
            The_Travelers_Companies float4 ,
            Trimble_Inc float4 ,
            Truist_Financial float4 ,
            Tyler_Technologies float4 ,
            Tyson_Foods float4 ,
            US_Bank float4 ,
            UDR float4 ,

            Ulta_Beauty float4 ,
            Union_Pacific_Corporation float4 ,
            United_Airlines_Holdings float4 ,
            United_Parcel_Service float4 ,
            United_Rentals float4 ,
            UnitedHealth_Group float4 ,
            Universal_Health_Services float4 ,
            Valero_Energy float4 ,
            Ventas float4 ,
            Verisign float4 ,
            Verisk float4 ,
            Verizon float4 ,
            Vertex_Pharmaceuticals float4 ,
            VF_Corporation float4 ,
            Viatris float4 ,
            Vici_Properties float4 ,
            Visa_Inc float4 ,
            Vulcan_Materials_Company float4 ,
            Wabtec float4 ,
            Walgreens_Boots_Alliance float4 ,
            Walmart float4 ,
            Warner_Bros_Discovery float4 ,
            Waste_Management float4 ,
            Waters_Corporation float4 ,
            WEC_Energy_Group float4 ,
            Wells_Fargo float4 ,
            Welltower float4 ,
            West_Pharmaceutical_Services float4 ,
            Western_Digital float4 ,
            WestRock float4 ,
            Weyerhaeuser float4 ,
            Whirlpool_Corporation float4 ,
            Williams_Companies float4 ,
            Willis_Towers_Watson float4 ,
            W_W_Grainger float4 ,
            Wynn_Resorts float4 ,
            Xcel_Energy float4 ,
            Xylem_Inc float4 ,
            Yum_Brands float4 ,
            Zebra_Technologies float4 ,
            Zimmer_Biomet float4 ,
            Zions_Bancorporation float4 ,
            Zoetis float4, 
               
                PRIMARY KEY (TresM)

               );""")


conn.commit()



new_columns = str("""TresM float4 ,
            A_O_Smith float4 ,
            Abbott_Laboratories float4 ,
            AbbVie float4 ,
            Accenture float4 ,
            Activision_Blizzard float4 ,
            ADM float4 ,
            Adobe_Inc float4 ,
            ADP float4 ,
            Advance_Auto_Parts float4 ,
            AES_Corporation float4 ,
            Aflac float4 ,
            Agilent_Technologies float4 ,
            Air_Products_and_Chemicals float4 ,
            Akamai float4 ,
            Alaska_Air_Group float4 ,
            Albemarle_Corporation float4 ,
            Alexandria_Real_Estate_Equities float4 ,
            Align_Technology float4 ,
            Allegion float4 ,
            Alliant_Energy float4 ,
            Allstate float4 ,
            Alphabet_Inc float4 ,
            Altria float4 ,
            Amazon float4 ,
            Amcor float4 ,
            AMD float4 ,
            Ameren float4 ,
            American_Airlines_Group float4 ,
            American_Electric_Power float4 ,
            American_Express float4 ,
            American_International_Group float4 ,
            American_Tower float4 ,
            American_Water_Works float4 ,
            Ameriprise_Financial float4 ,
            AmerisourceBergen float4 ,
            Ametek float4 ,
            Amgen float4 ,
            Amphenol float4 ,
            Analog_Devices float4 ,
            Ansys float4 ,
            Aon float4 ,
            APA_Corporation float4 ,
            Apple_Inc float4 ,
            Applied_Materials float4 ,
            Aptiv float4 ,
            Arch_Capital_Group float4 ,
            Arista_Networks float4 ,
            Arthur_J_Gallagher_and_Co float4 ,
            Assurant float4 ,
            ATandT float4 ,
            Atmos_Energy float4 ,
            Autodesk float4 ,
            AutoZone float4 ,
            AvalonBay_Communities float4 ,
            Avery_Dennison float4 ,
            Axon_Enterprise float4 ,
            Baker_Hughes float4 ,
            Ball_Corporation float4 ,
            Bank_of_America float4 ,
            Bath_and_Body_Works float4 ,

            Baxter_International float4 ,
            BD float4 ,
            W_R_Berkley_Corporation float4 ,
            Berkshire_Hathaway float4 ,
            Best_Buy float4 ,
            Bio_Rad float4 ,
            Bio_Techne float4 ,
            Biogen float4 ,
            BlackRock float4 ,
            BNY_Mellon float4 ,
            Boeing float4 ,
            Booking_Holdings float4 ,
            BorgWarner float4 ,
            Boston_Properties float4 ,
            Boston_Scientific float4 ,
            Bristol_Myers_Squibb float4 ,
            Broadcom_Inc float4 ,
            Broadridge_Financial_Solutions float4 ,
            Brown_and_Brown float4 ,
            Bunge_Limited float4 ,
            CH_Robinson float4 ,
            Cadence_Design_Systems float4 ,
            Caesars_Entertainment float4 ,
            Camden_Property_Trust float4 ,
            Campbell_Soup_Company float4 ,
            Capital_One float4 ,
            Cardinal_Health float4 ,
            CarMax float4 ,
            Carnival_Corporation_and_plc float4 ,
            Carrier_Global float4 ,
            Catalent float4 ,
            Caterpillar_Inc float4 ,
            Cboe_Global_Markets float4 ,
            CBRE_Group float4 ,
            CDW float4 ,
            Celanese float4 ,
            Centene_Corporation float4 ,
            CenterPoint_Energy float4 ,
            Ceridian float4 ,
            CF_Industries float4 ,
            Charles_River_Laboratories float4 ,
            Charles_Schwab_Corporation float4 ,
            Charter_Communications float4 ,
            Chevron_Corporation float4 ,
            Chipotle_Mexican_Grill float4 ,
            Chubb_Limited float4 ,
            Church_and_Dwight float4 ,
            Cigna float4 ,
            Cincinnati_Financial float4 ,
            Cintas float4 ,
            Cisco float4 ,
            Citigroup float4 ,
            Citizens_Financial_Group float4 ,
            Clorox float4 ,
            CME_Group float4 ,
            CMS_Energy float4 ,
            The_Coca_Cola_Company float4 ,
            Cognizant float4 ,
            Colgate_Palmolive float4 ,
            Comcast float4 ,
            Comerica float4 ,
            Conagra_Brands float4 ,
            ConocoPhillips float4 ,
            Consolidated_Edison float4 ,
            Constellation_Brands float4 ,
            Constellation_Energy float4 ,
            CooperCompanies float4 ,
            Copart float4 ,
            Corning_Inc float4 ,
            Corteva float4 ,
            CoStar_Group float4 ,
            Costco float4 ,
            Coterra float4 ,
            Crown_Castle float4 ,
            CSX_Corporation float4 ,
            Cummins float4 ,
            CVS_Health float4 ,
            DR_Horton float4 ,
            Danaher_Corporation float4 ,
            Darden_Restaurants float4 ,
            DaVita_Inc float4 ,
            John_Deere float4 ,
            Delta_Air_Lines float4 ,
            Dentsply_Sirona float4 ,
            Devon_Energy float4 ,
            Dexcom float4 ,
            Diamondback_Energy float4 ,
            Digital_Realty float4 ,
            Discover_Financial float4 ,
            Disney float4 ,
            Dollar_General float4 ,
            Dollar_Tree float4 ,
            Dominion_Energy float4 ,
            Domino float4 ,
            Dover_Corporation float4 ,
            Dow_Inc float4 ,
            DTE_Energy float4 ,
            Duke_Energy float4 ,
            DuPont float4 ,
            DXC_Technology float4 ,
            Eastman_Chemical_Company float4 ,
            Eaton_Corporation float4 ,
            EBay float4 ,
            Ecolab float4 ,
            Edison_International float4 ,
            Edwards_Lifesciences float4 ,
            Electronic_Arts float4 ,
            Elevance_Health float4 ,
            Eli_Lilly_and_Company float4 ,
            Emerson_Electric float4 ,
            Enphase float4 ,
            Entergy float4 ,
            EOG_Resources float4 ,
            EPAM_Systems float4 ,
            EQT float4 ,
            Equifax float4 ,
            Equinix float4 ,
            Equity_Residential float4 ,
            Essex_Property_Trust float4 ,
            The_Estée_Lauder_Companies float4 ,
            Etsy float4 ,
            Everest_Re float4 ,
            Evergy float4 ,
            Eversource float4 ,
            Exelon float4 ,
            Expedia_Group float4 ,
            Expeditors_International float4 ,
            Extra_Space_Storage float4 ,
            ExxonMobil float4 ,
            F5 float4 ,
            FactSet float4 ,
            FICO float4 ,
            Fastenal float4 ,
            Federal_Realty float4 ,
            FedEx float4 ,
            Fifth_Third_Bank float4 ,
            First_Solar float4 ,
            FirstEnergy float4 ,
            FIS float4 ,
            Fiserv float4 ,
            Fleetcor float4 ,
            FMC_Corporation float4 ,
            Ford_Motor_Company float4 ,
            Fortinet float4 ,
            Fortive float4 ,
            Fox_Corporation float4 ,
            Franklin_Templeton float4 ,
            Freeport_McMoRan float4 ,
            Garmin float4 ,
            Gartner float4 ,
            GE_HealthCare float4 ,
            Gen_Digital float4 ,
            Generac float4 ,
            General_Dynamics float4 ,
            General_Electric float4 ,
            General_Mills float4 ,
            General_Motors float4 ,
            Genuine_Parts_Company float4 ,
            Gilead_Sciences float4 ,
            Globe_Life float4 ,
            Global_Payments float4 ,
            Goldman_Sachs float4 ,
            Halliburton float4 ,
            The_Hartford float4 ,
            Hasbro float4 ,
            HCA_Healthcare float4 ,
            Healthpeak_Properties float4 ,
            Henry_Schein float4 ,
            The_Hershey_Company float4 ,
            Hess_Corporation float4 ,
            Hewlett_Packard_Enterprise float4 ,
            Hilton_Worldwide float4 ,
            Hologic float4 ,
            The_Home_Depot float4 ,
            Honeywell float4 ,
            Hormel_Foods float4 ,
            Host_Hotels_and_Resorts float4 ,
            Howmet_Aerospace float4 ,
            HP_Inc float4 ,
            Humana float4 ,
            Huntington_Bancshares float4 ,
            Huntington_Ingalls_Industries float4 ,
            IBM float4 ,
            IDEX_Corporation float4 ,
            Idexx_Laboratories float4 ,
            Illinois_Tool_Works float4 ,
            Illumina float4 ,

            Incyte float4 ,
            Ingersoll_Rand float4 ,
            Intel float4 ,
            Intercontinental_Exchange float4 ,
            International_Flavors_and_Fragrances float4 ,
            International_Paper float4 ,
            The_Interpublic_Group_of_Companies float4 ,
            Intuit float4 ,
            Intuitive_Surgical float4 ,
            Invesco float4 ,
            Invitation_Homes float4 ,
            IQVIA float4 ,
            Iron_Mountain float4 ,
            JB_Hunt float4 ,
            Jack_Henry_and_Associates float4 ,
            Jacobs_Solutions float4 ,
            Johnson_and_Johnson float4 ,
            Johnson_Controls float4 ,
            JPMorgan_Chase float4 ,
            Juniper_Networks float4 ,
            Kellogg float4 ,
            Keurig_Dr_Pepper float4 ,
            KeyBank float4 ,
            Keysight float4 ,
            Kimberly_Clark float4 ,
            Kimco_Realty float4 ,
            Kinder_Morgan float4 ,
            KLA_Corporation float4 ,
            Kraft_Heinz float4 ,
            Kroger float4 ,
            L3Harris float4 ,
            LabCorp float4 ,
            Lam_Research float4 ,
            Lamb_Weston float4 ,
            Las_Vegas_Sands float4 ,
            Leidos float4 ,
            Lennar float4 ,
            Lincoln_Financial float4 ,
            Linde_plc float4 ,
            Live_Nation_Entertainment float4 ,
            LKQ_Corporation float4 ,
            Lockheed_Martin float4 ,
            Loews_Corporation float4 ,
            Lowe float4 ,
            LyondellBasell float4 ,
            MandT_Bank float4 ,
            Marathon_Oil float4 ,
            Marathon_Petroleum float4 ,
            MarketAxess float4 ,
            Marriott_International float4 ,
            Marsh_McLennan float4 ,
            Martin_Marietta_Materials float4 ,
            Masco float4 ,
            Mastercard float4 ,
            Match_Group float4 ,
            McCormick_and_Company float4 ,
            McDonald float4 ,
            McKesson float4 ,
            Medtronic float4 ,
            Merck_and_Co float4 ,
            Meta_Platforms float4 ,
            MetLife float4 ,
            Mettler_Toledo float4 ,
            MGM_Resorts float4 ,
            Microchip_Technology float4 ,
            Micron_Technology float4 ,
            Microsoft float4 ,
            Mid_America_Apartment_Communities float4 ,
            Moderna float4 ,
            Mohawk_Industries float4 ,
            Molina_Healthcare float4 ,
            Molson_Coors_Beverage_Company float4 ,
            Mondelez_International float4 ,
            Monolithic_Power_Systems float4 ,
            Monster_Beverage float4 ,
            Moody_Corporation float4 ,
            Morgan_Stanley float4 ,
            The_Mosaic_Company float4 ,
            Motorola_Solutions float4 ,
            MSCI float4 ,
            Nasdaq float4 ,
          
            NetApp float4 ,
            Netflix float4 ,
 
            Newell_Brands float4 ,
            Newmont float4 ,
            News_Corp float4 ,
            NextEra_Energy float4 ,
            Nike float4 ,
   
            NiSource float4 ,
            Nordson_Corporation float4 ,
            Norfolk_Southern_Railway float4 ,
            Northern_Trust float4 ,
            Northrop_Grumman float4 ,
            Norwegian_Cruise_Line_Holdings float4 ,
            NRG_Energy float4 ,
            Nucor float4 ,
            Nvidia float4 ,
            NVR float4 ,

            NXP_Semiconductors float4 ,
            OReilly_Auto_Parts float4 ,
            Occidental_Petroleum float4 ,
            Old_Dominion_Freight_Line float4 ,
            Omnicom_Group float4 ,
            ON_Semiconductor float4 ,
            Oneok float4 ,
            Oracle_Corporation float4 ,
            Organon_and_Co float4 ,
            Otis_Worldwide float4 ,
            Paccar float4 ,
            Packaging_Corporation_of_America float4 ,
            Palo_Alto_Networks float4 ,
            Paramount_Global float4 ,
            Parker_Hannifin float4 ,
            Paychex float4 ,
            Paycom float4 ,
            PayPal float4 ,
            Pentair float4 ,
            PepsiCo float4 ,
            Pfizer float4 ,
            PGandE float4 ,
            Philip_Morris_International float4 ,
            Phillips_66 float4 ,
            Pinnacle_West float4 ,
            Pioneer_Natural_Resources float4 ,
            PNC_Financial_Services float4 ,
            PPG_Industries float4 ,
            PPL_Corporation float4 ,
            Principal_Financial_Group float4 ,
            Procter_and_Gamble float4 ,
            Progressive_Corporation float4 ,
            Prologis float4 ,
            Prudential_Financial float4 ,
            Public_Service_Enterprise_Group float4 ,
            PTC float4 ,
            Public_Storage float4 ,
            PulteGroup float4 ,
            Qorvo float4 ,
            Quanta_Services float4 ,
            Qualcomm float4 ,
            Quest_Diagnostics float4 ,
            Ralph_Lauren_Corporation float4 ,
            Raymond_James float4 ,
            Raytheon_Technologies float4 ,
            Realty_Income float4 ,
            Regency_Centers float4 ,
            Regeneron float4 ,
            Regions_Financial_Corporation float4 ,
            Republic_Services float4 ,
            ResMed float4 ,
            Revvity float4 ,
            Robert_Half float4 ,
            Rockwell_Automation float4 ,
            Rollins float4 ,
       
            Roper_Technologies float4 ,
            Ross_Stores float4 ,
            Royal_Caribbean_Group float4 ,
            SandP_Global float4 ,
            Salesforce float4 ,
            SBA_Communications float4 ,
            Schlumberger float4 ,
            Seagate_Technology float4 ,
            Sealed_Air float4 ,
            Sempra_Energy float4 ,
            ServiceNow float4 ,
            Sherwin_Williams float4 ,
            Simon_Property_Group float4 ,
            Skyworks_Solutions float4 ,
            The_JM_Smucker_Company float4 ,
            Snap_on float4 ,
            SolarEdge float4 ,
            Southern_Company float4 ,
            Southwest_Airlines float4 ,
            Stanley_Black_and_Decker float4 ,
            Starbucks float4 ,
            State_Street_Corporation float4 ,
            Steel_Dynamics float4 ,
            Steris float4 ,
            Stryker_Corporation float4 ,
            Synchrony_Financial float4 ,
            Synopsys float4 ,
            Sysco float4 ,
            T_Mobile_US float4 ,
            T_Rowe_Price float4 ,
            Take_Two_Interactive float4 ,
            Tapestry float4 ,

            Targa_Resources float4 ,
            Target_Corporation float4 ,
            TE_Connectivity float4 ,
            Teledyne_Technologies float4 ,
            Teleflex float4 ,
            Teradyne float4 ,
            Tesla float4 ,

            Texas_Instruments float4 ,
            Textron float4 ,
            Thermo_Fisher_Scientific float4 ,
            TJX_Companies float4 ,
            Tractor_Supply float4 ,
            Trane_Technologies float4 ,
            TransDigm_Group float4 ,
            The_Travelers_Companies float4 ,
            Trimble_Inc float4 ,
            Truist_Financial float4 ,
            Tyler_Technologies float4 ,
            Tyson_Foods float4 ,
            US_Bank float4 ,
            UDR float4 ,

            Ulta_Beauty float4 ,
            Union_Pacific_Corporation float4 ,
            United_Airlines_Holdings float4 ,
            United_Parcel_Service float4 ,
            United_Rentals float4 ,
            UnitedHealth_Group float4 ,
            Universal_Health_Services float4 ,
            Valero_Energy float4 ,
            Ventas float4 ,
            Verisign float4 ,
            Verisk float4 ,
            Verizon float4 ,
            Vertex_Pharmaceuticals float4 ,
            VF_Corporation float4 ,
            Viatris float4 ,
            Vici_Properties float4 ,
            Visa_Inc float4 ,
            Vulcan_Materials_Company float4 ,
            Wabtec float4 ,
            Walgreens_Boots_Alliance float4 ,
            Walmart float4 ,
            Warner_Bros_Discovery float4 ,
            Waste_Management float4 ,
            Waters_Corporation float4 ,
            WEC_Energy_Group float4 ,
            Wells_Fargo float4 ,
            Welltower float4 ,
            West_Pharmaceutical_Services float4 ,
            Western_Digital float4 ,
            WestRock float4 ,
            Weyerhaeuser float4 ,
            Whirlpool_Corporation float4 ,
            Williams_Companies float4 ,
            Willis_Towers_Watson float4 ,
            W_W_Grainger float4 ,
            Wynn_Resorts float4 ,
            Xcel_Energy float4 ,
            Xylem_Inc float4 ,
            Yum_Brands float4 ,
            Zebra_Technologies float4 ,
            Zimmer_Biomet float4 ,
            Zions_Bancorporation float4 ,
            Zoetis float4'
            """)



column_list = [column.strip() for column in new_columns.strip().split(',')]

no_float = [item.replace(' float4', '') for item in column_list]

# remove unwanted strings 

columns_df = [item.replace("'", '') for item in no_float]





#6 


df_final.columns = columns_df


from utils_subir import execute_values_change_on_primary_k


#7  Subimos la tabla!

execute_values_change_on_primary_k(conn=conn, # conexion sin el cursor
                                   df=df_final, # df a subir. imp tener mismo orden y nombre de columnas aqui que en bbdd
                                   schema_table="public.embeddings_sentencetransformer", # nombre de tabla
                                   primary_k_tuple='(TresM)', # siempre en este formato
                                   lista_conflict=list(df_final.columns[1:]), # colums que quieres cambiar en conflicto
                                   close_connection="yes") 

conn.commit()
#### pasos quye hemos echo 

"""

1. sacar e listado y pasarlo a excel 

2, listado de escel ceamos tabla

3 limpiar a mano los nombres que no son validados para nombra una columna de una tabla 

4. borrar .inc

5. crear un nuevo listado de columna en base a la tabla creada 

6. renombrar columns 

7 . subir tabla 


"""



